# Generated by Django 2.2.5 on 2020-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_profile_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(related_name='following', to='events.Profile'),
        ),
    ]
